a=int(input("Enter the first number : "))
b=int(input("Enter the second number :"))
print("\n\nRelational Operator\n\n")
print("a==b ",a==b)
print("a!=b ",a!=b)
print("a>b  ",a>b)
print("a>=b ",a>=b)
print("a<b  ",a<b)
print("a<=b ",a<=b)

